stages:
  data_ingestion:
    cmd: python -m networksecurity.pipeline.training_pipeline --stage data_ingestion
    deps:
      - networksecurity/pipeline/training_pipeline.py
      - networksecurity/components/data_ingestion.py
    outs:
      - artifact/data_ingestion

  data_validation:
    cmd: python -m networksecurity.pipeline.training_pipeline --stage data_validation
    deps:
      - networksecurity/pipeline/training_pipeline.py
      - networksecurity/components/data_validation.py
      - artifact/data_ingestion
    outs:
      - artifact/data_validation

  data_transformation:
    cmd: python -m networksecurity.pipeline.training_pipeline --stage data_transformation
    deps:
      - networksecurity/pipeline/training_pipeline.py
      - networksecurity/components/data_transformation.py
      - artifact/data_validation
    outs:
      - artifact/data_transformation

  model_training:
    cmd: python -m networksecurity.pipeline.training_pipeline --stage model_trainer
    deps:
      - networksecurity/pipeline/training_pipeline.py
      - networksecurity/components/model_trainer.py
      - artifact/data_transformation
    outs:
      - artifact/model_trainer
    metrics:
      - reports/metrics.json:
          cache: false
          
  direct_training:
    cmd: python train_with_components.py
    deps:
      - train_with_components.py
      - networksecurity/components/data_transformation.py
      - networksecurity/components/model_trainer.py
      - custom_model_trainer.py
      - Network_Data/cyber_threat_intelligence_train.csv
    outs:
      - artifact/direct_training
    metrics:
      - reports/direct_training_metrics.json:
          cache: false

