name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'tests/**'
      - 'requirements.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up venv and install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          source venv/bin/activate
          pytest -q
